# Generated by Django 5.2.3 on 2026-02-24 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_quick_tip_dont_say_in_interview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyPartnershipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(blank=True, max_length=255)),
                ('primary_contact_name', models.CharField(blank=True, max_length=255)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('website', models.URLField(blank=True)),
                ('physical_address', models.CharField(blank=True, max_length=255)),
                ('service_area', models.CharField(blank=True, help_text='City / ZIP coverage', max_length=255)),
                ('year_founded', models.PositiveIntegerField(blank=True, null=True)),
                ('organization_type', models.CharField(blank=True, choices=[('nonprofit', 'Nonprofit'), ('for_profit', 'For-Profit'), ('government', 'Government')], max_length=32)),
                ('services_offered', models.JSONField(blank=True, default=list)),
                ('services_other', models.CharField(blank=True, max_length=255)),
                ('target_population', models.JSONField(blank=True, default=list)),
                ('target_population_other', models.CharField(blank=True, max_length=255)),
                ('supports_justice_impacted', models.BooleanField(default=False)),
                ('supports_recently_released', models.BooleanField(default=False)),
                ('average_served_per_month', models.PositiveIntegerField(blank=True, null=True)),
                ('intake_process_description', models.TextField(blank=True)),
                ('referral_method_preference', models.CharField(blank=True, choices=[('website_link', 'Direct website link'), ('email_referral', 'Email referral'), ('phone_referral', 'Phone referral'), ('api_future', 'API integration (future)')], max_length=32)),
                ('tracks_employment_outcomes', models.BooleanField(blank=True, null=True)),
                ('open_to_referral_tracking', models.BooleanField(blank=True, null=True)),
                ('partnership_reason', models.TextField(blank=True)),
                ('reroute_support_needs', models.TextField(blank=True)),
                ('interested_in_featured_verified', models.BooleanField(blank=True, null=True)),
                ('accuracy_confirmation', models.BooleanField(default=False)),
                ('terms_privacy_agreement', models.BooleanField(default=False)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partner_logos/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('in_review', 'In Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_agency_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
