# Generated by Django 5.2.3 on 2026-02-24 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_agencypartnershipapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencypartnershipapplication',
            name='additional_eligibility_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='agencypartnershipapplication',
            name='requires_government_id',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agencypartnershipapplication',
            name='requires_intake_assessment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agencypartnershipapplication',
            name='requires_orientation_attendance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agencypartnershipapplication',
            name='requires_release_window',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agencypartnershipapplication',
            name='requires_service_area_residency',
            field=models.BooleanField(default=False),
        ),
    ]
