# Generated by Django 5.2.3 on 2025-09-16 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_analyticsevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticsevent',
            name='event_type',
            field=models.CharField(choices=[('page_view', 'Page View'), ('profile_view', 'Profile View'), ('profile_created', 'Profile Created'), ('profile_updated', 'Profile Updated'), ('profile_completed', 'Profile Completed'), ('resume_created', 'Resume Created'), ('resume_updated', 'Resume Updated')], db_index=True, max_length=64),
        ),
    ]
