# Generated by Django 5.2.3 on 2026-02-09 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_onboarding_event'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='onboardingevent',
            new_name='core_onboar_event_acd998_idx',
            old_name='core_onboar_event_e79a28_idx',
        ),
    ]
