# Generated by Django 5.2.3 on 2025-09-09 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('page_view', 'Page View'), ('profile_created', 'Profile Created'), ('profile_updated', 'Profile Updated'), ('profile_completed', 'Profile Completed'), ('resume_created', 'Resume Created'), ('resume_updated', 'Resume Updated')], db_index=True, max_length=64)),
                ('path', models.CharField(blank=True, help_text='Request path if applicable', max_length=512)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='core_analyt_event_t_2d093d_idx')],
            },
        ),
    ]
