# Generated by Django 5.2.3 on 2025-09-16 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='verification_notes',
            field=models.TextField(blank=True, help_text='Internal notes for verification decisions'),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='verified',
            field=models.BooleanField(default=False, help_text='Manually verified by ReRoute staff'),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
