# Generated by Codex on 2026-01-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0007_userprofile_onboarding_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="Language",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="userprofile",
            name="languages",
            field=models.ManyToManyField(blank=True, to="profiles.language"),
        ),
    ]
