# Generated by Codex on 2026-01-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0008_language_and_userprofile_languages"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="background_gradient",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
