# Generated by Django 5.2.3 on 2026-02-24 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_userprofile_geo_point_and_zip_code'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='ALTER TABLE "profiles_userprofile" DROP COLUMN IF EXISTS "geo_point";',
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='userprofile',
                    name='geo_point',
                ),
            ],
        ),
    ]
