# Generated by Django 5.2.3 on 2025-09-09 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_alter_contactinfo_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='certifications',
            field=models.TextField(blank=True, help_text='One per line. Optional.'),
        ),
    ]
