# Generated by Django 5.2.3 on 2025-09-16 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0004_resume_preview_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='template',
            field=models.CharField(choices=[('reroute', 'ReRoute'), ('professional', 'Professional'), ('modern', 'Modern'), ('simple', 'Simple')], default='reroute', max_length=20),
        ),
    ]
