# Generated by Django 5.2.3 on 2025-08-18 01:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('website', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employerprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=50)),
                ('lastname', models.CharField(blank=True, max_length=50)),
                ('preferred_name', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('personal_email', models.EmailField(blank=True, max_length=254)),
                ('street_address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('bio', models.TextField(blank=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('pronouns', models.CharField(blank=True, max_length=50)),
                ('native_language', models.CharField(blank=True, max_length=100)),
                ('year_of_incarceration', models.IntegerField(blank=True, null=True)),
                ('year_released', models.IntegerField(blank=True, null=True)),
                ('relation_to_reroute', models.CharField(blank=True, max_length=100)),
                ('emergency_contact_firstname', models.CharField(blank=True, max_length=100)),
                ('emergency_contact_lastname', models.CharField(blank=True, max_length=100)),
                ('emergency_contact_relationship', models.CharField(blank=True, max_length=100)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20)),
                ('emergency_contact_email', models.EmailField(blank=True, max_length=254)),
                ('gender', models.CharField(blank=True, max_length=50)),
                ('ethnicity', models.CharField(blank=True, max_length=50)),
                ('race', models.JSONField(blank=True, default=list, null=True)),
                ('disability', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True)),
                ('veteran_status', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True)),
                ('disability_explanation', models.TextField(blank=True, null=True)),
                ('veteran_explanation', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('', 'Select a status'), ('actively_seeking', 'Actively Seeking Work'), ('recently_released', 'Recently Released'), ('employed', 'Employed'), ('in_training', 'In Training or Education'), ('not_ready', 'Not Currently Seeking'), ('need_support', 'Needs Additional Support')], help_text='User-defined status reflecting their current journey.', max_length=30)),
                ('account_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', help_text='Platform-controlled account state.', max_length=20)),
                ('verified', models.BooleanField(default=True, help_text="Show a verified badge on this user's public profile.")),
                ('work_in_us', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
                ('sponsorship_needed', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
                ('lgbtq', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
                ('user_uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('skills', models.ManyToManyField(blank=True, to='core.skill')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ['user_uid'],
            },
        ),
    ]
