# Generated by Django 5.2.3 on 2025-09-08 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='flagged_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
    ]
