# Generated by Django 5.2.3 on 2026-02-23 03:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def promote_existing_posts(apps, schema_editor):
    BlogPost = apps.get_model('blog', 'BlogPost')
    category_map = {
        'tips': 'tips',
        'legal': 'reentry',
        'news': 'updates',
        'motivation': 'story',
        'success': 'story',
        'tech': 'story',
        'other': 'story',
        'general': 'story',
    }

    for post in BlogPost.objects.all():
        post.visibility = 'public'
        post.category = category_map.get(post.category, 'story')
        post.save(update_fields=['visibility', 'category'])


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='private', max_length=20),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('journal', 'Journal'), ('story', 'Story'), ('fair_chance', 'Fair-Chance Hiring'), ('tips', 'Job Seeker Tips'), ('updates', 'Platform Updates'), ('reentry', 'Reentry Orgs')], default='journal', max_length=40),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.RunPython(promote_existing_posts, migrations.RunPython.noop),
    ]
