# Generated by Django 5.2.3 on 2026-02-22 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_list', '0006_savedcandidate'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='jobinvitation',
            new_name='job_list_jo_employe_e9eba9_idx',
            old_name='job_list_j_employe_96c1db_idx',
        ),
        migrations.RenameIndex(
            model_name='jobinvitation',
            new_name='job_list_jo_employe_445184_idx',
            old_name='job_list_j_employe_e619b7_idx',
        ),
        migrations.RenameIndex(
            model_name='savedcandidate',
            new_name='job_list_sa_saved_b_118e64_idx',
            old_name='savedcand_user_idx',
        ),
        migrations.AlterField(
            model_name='savedcandidate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
