# Generated by Django 5.2.3 on 2026-02-23 18:25

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_core_onboar_event_e79a28_idx_core_onboar_event_acd998_idx'),
        ('job_list', '0008_postgis_zipcentroid_and_geo_points'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='job',
            name='job_list_jo_geo_p_681e90_idx',
        ),
        migrations.RemoveIndex(
            model_name='zipcentroid',
            name='job_list_zi_geo_p_3a6fa1_idx',
        ),
        migrations.AddField(
            model_name='job',
            name='is_remote',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='job',
            index=django.contrib.postgres.indexes.GistIndex(fields=['geo_point'], name='job_list_jo_geo_poi_58626e_gist'),
        ),
        migrations.AddIndex(
            model_name='zipcentroid',
            index=django.contrib.postgres.indexes.GistIndex(fields=['geo_point'], name='job_list_zi_geo_poi_cd9010_gist'),
        ),
    ]
