# Generated by Django 5.2.3 on 2026-02-24 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_list', '0009_remove_job_job_list_jo_geo_p_681e90_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='job',
            name='job_list_jo_geo_poi_58626e_gist',
        ),
        migrations.RemoveIndex(
            model_name='zipcentroid',
            name='job_list_zi_geo_poi_cd9010_gist',
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='ALTER TABLE "job_list_job" DROP COLUMN IF EXISTS "geo_point";',
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql='ALTER TABLE "job_list_zipcentroid" DROP COLUMN IF EXISTS "geo_point";',
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='job',
                    name='geo_point',
                ),
                migrations.RemoveField(
                    model_name='zipcentroid',
                    name='geo_point',
                ),
            ],
        ),
    ]
