# Generated by Django 5.2.3 on 2025-09-08 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='target_group',
            field=models.CharField(blank=True, choices=[('ALL', 'All Users'), ('EMPLOYERS', 'Employers'), ('SEEKERS', 'Job Seekers')], help_text='Leave blank for direct messages; choose a group to broadcast', max_length=10),
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(blank=True, help_text='Short title for admin messages', max_length=200),
        ),
        migrations.AlterField(
            model_name='notification',
            name='actor',
            field=models.ForeignKey(blank=True, help_text='User who triggered the event (for action notifications)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actor_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='url',
            field=models.CharField(blank=True, help_text='Optional link for CTA', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Target user for direct notifications. Leave empty for broadcasts.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(blank=True, help_text='Action verb (e.g., applied)', max_length=100),
        ),
    ]
