# Generated by Django 5.2.3 on 2025-09-16 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_notification_target_group_notification_title_and_more'),
        ('job_list', '0002_job_flagged_reason_job_is_flagged'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField(db_index=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('rescheduled', 'Rescheduled'), ('completed', 'Completed'), ('canceled', 'Canceled')], db_index=True, default='planned', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_interviews', to=settings.AUTH_USER_MODEL)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employer_interviews', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='job_list.job')),
            ],
            options={
                'ordering': ['scheduled_at', 'id'],
                'indexes': [models.Index(fields=['employer', 'scheduled_at'], name='dashboard_i_employe_448320_idx'), models.Index(fields=['candidate', 'scheduled_at'], name='dashboard_i_candida_4c4f7d_idx'), models.Index(fields=['job', 'scheduled_at'], name='dashboard_i_job_id_a2426f_idx')],
            },
        ),
    ]
