# Generated by Django 5.2.3 on 2026-02-24 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reentry_org', '0004_reentryorganization_geo_point_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reentryorganization',
            options={'ordering': ['-is_verified', 'name']},
        ),
        migrations.RemoveIndex(
            model_name='reentryorganization',
            name='reentry_org_geo_poi_bdb4dd_gist',
        ),
        migrations.RemoveField(
            model_name='reentryorganization',
            name='geo_point',
        ),
    ]
