# Generated by Django 5.2.3 on 2026-02-25 00:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reentry_org', '0005_alter_reentryorganization_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReentryOrgApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(db_index=True, max_length=255)),
                ('primary_contact_name', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(db_index=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('website', models.URLField(blank=True)),
                ('physical_address', models.CharField(blank=True, max_length=255)),
                ('service_area', models.CharField(blank=True, help_text='City / ZIP coverage', max_length=255)),
                ('year_founded', models.PositiveIntegerField(blank=True, null=True)),
                ('organization_type', models.CharField(blank=True, choices=[('nonprofit', 'Nonprofit'), ('for_profit', 'For-Profit'), ('government', 'Government')], max_length=32)),
                ('services', models.JSONField(blank=True, default=list)),
                ('other_services', models.CharField(blank=True, max_length=255)),
                ('serve_justice_impacted', models.BooleanField(default=False)),
                ('serve_recently_released', models.BooleanField(default=False)),
                ('additional_populations', models.JSONField(blank=True, default=list)),
                ('other_populations', models.CharField(blank=True, max_length=255)),
                ('program_criteria', models.TextField(blank=True)),
                ('requires_id', models.BooleanField(default=False)),
                ('requires_orientation', models.BooleanField(default=False)),
                ('requires_intake_assessment', models.BooleanField(default=False)),
                ('requires_residency_in_service_area', models.BooleanField(default=False)),
                ('avg_served_per_month', models.PositiveIntegerField(blank=True, null=True)),
                ('intake_process_description', models.TextField(blank=True)),
                ('preferred_referral_method', models.CharField(blank=True, choices=[('website', 'Direct website link'), ('email', 'Email referral'), ('phone', 'Phone referral'), ('api_future', 'API integration (future)')], max_length=32)),
                ('tracks_employment_outcomes', models.BooleanField(blank=True, null=True)),
                ('open_to_referral_tracking', models.BooleanField(blank=True, null=True)),
                ('why_partner', models.TextField(blank=True)),
                ('how_reroute_can_support', models.TextField(blank=True)),
                ('interested_featured_verified', models.BooleanField(blank=True, null=True)),
                ('accuracy_confirmation', models.BooleanField(default=False)),
                ('terms_privacy_agreement', models.BooleanField(default=False)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='reentry_org_application_logos/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reentry_org_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reentry Org Application',
                'verbose_name_plural': 'Reentry Org Applications',
                'ordering': ('-submitted_at', '-id'),
            },
        ),
    ]
