# Generated by Django 5.2.3 on 2026-02-25 03:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reentry_org', '0006_reentryorgapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='reentryorgapplication',
            name='application_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
