# Generated by Django 5.2.7 on 2025-10-15 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reentry_org', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='reentryorganization',
            new_name='reentry_org_is_veri_f81942_idx',
            old_name='reentry_org_verified_category_idx',
        ),
    ]
