# Generated by Codex on 2025-02-15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("resumes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="headline",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="resume",
            name="is_complete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="resume",
            name="last_step",
            field=models.CharField(blank=True, default="basics", max_length=32),
        ),
        migrations.AddField(
            model_name="resume",
            name="section_order",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="resume",
            name="step_basics_complete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="resume",
            name="step_education_complete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="resume",
            name="step_experience_complete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="resume",
            name="step_review_complete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="resume",
            name="step_skills_complete",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="education",
            name="school",
            field=models.CharField(blank=True, max_length=255, verbose_name="School / Program / Training Name"),
        ),
        migrations.AlterField(
            model_name="education",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="education",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="education",
            name="details",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="education",
            name="field_of_study",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="education",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="education",
            name="year",
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name="experience",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="experience",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="experience",
            name="end_year",
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name="experience",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="experience",
            name="responsibilities",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="experience",
            name="role_type",
            field=models.CharField(choices=[("job", "Job"), ("other", "Other experience / programs")], default="job", max_length=40),
        ),
        migrations.AddField(
            model_name="experience",
            name="start_year",
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name="experience",
            name="tools",
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name="EducationType",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
        migrations.AddField(
            model_name="education",
            name="education_type",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="education_entries", to="resumes.educationtype"),
        ),
        migrations.CreateModel(
            name="ResumeSkill",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("category", models.CharField(choices=[("technical", "Technical/Hard Skills"), ("soft", "Soft Skills & Strengths")], max_length=20)),
                ("order", models.PositiveIntegerField(default=0)),
                ("resume", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="categorized_skills", to="resumes.resume")),
                ("skill", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="resume_links", to="core.skill")),
            ],
            options={
                "ordering": ["order", "id"],
                "unique_together": {("resume", "skill")},
            },
        ),
    ]
