# Generated by Codex on 2025-02-15

from django.db import migrations


def seed_education_types(apps, schema_editor):
    EducationType = apps.get_model("resumes", "EducationType")
    options = [
        "HS Diploma/GED",
        "Certificate",
        "Associate",
        "Bachelor",
        "Master",
        "Trade Program",
        "Bootcamp",
        "Training Program",
        "Other",
    ]
    for idx, name in enumerate(options):
        EducationType.objects.get_or_create(name=name, defaults={"order": idx})


def unseed_education_types(apps, schema_editor):
    EducationType = apps.get_model("resumes", "EducationType")
    EducationType.objects.filter(name__in=[
        "HS Diploma/GED",
        "Certificate",
        "Associate",
        "Bachelor",
        "Master",
        "Trade Program",
        "Bootcamp",
        "Training Program",
        "Other",
    ]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0002_resume_builder_revamp"),
    ]

    operations = [
        migrations.RunPython(seed_education_types, unseed_education_types),
    ]
