# Generated by Django 5.2.3 on 2026-02-11 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0003_seed_education_types'),
        ('resumes', '0005_alter_resume_template'),
    ]

    operations = [
    ]
