# Generated by Django 5.2.3 on 2025-08-18 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('job', 'Job Tools'), ('tech', 'Tech Training'), ('reentry', 'Reentry Support'), ('video', 'How-To Video')], max_length=50)),
                ('link', models.URLField(blank=True)),
                ('video_embed', models.TextField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
    ]
