# Generated by Django 5.2.7 on 2025-11-04 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('workforce', 'Workforce Readiness'), ('digital', 'Digital Skills'), ('reentry', 'Reentry Support'), ('life', 'Life Skills')], max_length=50)),
                ('embed_html', models.TextField(blank=True, null=True)),
                ('internal_content', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Learning Module',
                'verbose_name_plural': 'Learning Modules',
            },
        ),
    ]
