# Generated by Django 5.2.3 on 2025-11-14 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_module_quiz_system'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='qtype',
            field=models.CharField(choices=[('mc', 'Multiple Choice'), ('open', 'Open Ended')], default='mc', max_length=10),
        ),
        migrations.CreateModel(
            name='ModuleQuizOpenResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_responses', to='resources.module')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_responses', to='resources.quizquestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_quiz_open_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('module', 'question', 'user'), name='unique_open_response')],
            },
        ),
    ]
