# Generated by Django 5.2.3 on 2025-11-14 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_quizquestion_qtype_modulequizopenresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='poster_image',
            field=models.ImageField(blank=True, null=True, upload_to='modules/posters/'),
        ),
    ]
