# Generated by Django 5.2.3 on 2026-02-22 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0011_feature_model_and_resourceorganization_features_m2m'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resourceorganization',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='resourceorganization',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
