# Generated by Django 5.2.3 on 2026-02-23 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0012_alter_resourceorganization_options_and_more'),
        ('resources', '0012_resourceorganization_category_and_canonical_features'),
    ]

    operations = [
    ]
