# Generated by Django 5.2.3 on 2026-02-23 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0015_seed_expanded_canonical_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceorganization',
            name='hours',
            field=models.TextField(blank=True),
        ),
    ]
