# Generated by Django 5.2.3 on 2026-02-23 18:45

import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
from django.db import migrations


def _normalize_zip(zip_code):
    raw = (zip_code or "").strip()
    if not raw:
        return ""
    return raw.split("-")[0][:5]


def _backfill_resource_geo_points(apps, schema_editor):
    ResourceOrganization = apps.get_model("resources", "ResourceOrganization")
    ZipCentroid = apps.get_model("job_list", "ZipCentroid")

    centroid_map = dict(ZipCentroid.objects.values_list("zip_code", "geo_point"))
    updates = []
    for resource in ResourceOrganization.objects.all().only("id", "zip_code", "geo_point"):
        normalized_zip = _normalize_zip(resource.zip_code)
        point = centroid_map.get(normalized_zip)
        if point is None:
            continue
        if resource.geo_point:
            continue
        resource.geo_point = point
        updates.append(resource)

    if updates:
        ResourceOrganization.objects.bulk_update(updates, ["geo_point"], batch_size=1000)


class Migration(migrations.Migration):

    dependencies = [
        ('job_list', '0009_remove_job_job_list_jo_geo_p_681e90_idx_and_more'),
        ('resources', '0016_alter_resourceorganization_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourceorganization',
            name='geo_point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
        migrations.AddIndex(
            model_name='resourceorganization',
            index=django.contrib.postgres.indexes.GistIndex(fields=['geo_point'], name='resources_r_geo_poi_60d854_gist'),
        ),
        migrations.RunPython(_backfill_resource_geo_points, migrations.RunPython.noop),
    ]
