# Generated by Django 5.2.3 on 2026-02-24 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0019_seed_clothing_and_vital_documents_features'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resourceorganization',
            options={'ordering': ('-is_verified', 'name')},
        ),
        migrations.RemoveIndex(
            model_name='resourceorganization',
            name='resources_r_geo_poi_60d854_gist',
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='ALTER TABLE "resources_resourceorganization" DROP COLUMN IF EXISTS "geo_point";',
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='resourceorganization',
                    name='geo_point',
                ),
            ],
        ),
    ]
