# Generated by Django 5.2.3 on 2026-03-19 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0025_moduleprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonquestion',
            name='explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='explanation',
            field=models.TextField(blank=True),
        ),
    ]
